<a href="https://colab.research.google.com/github/Ghhaidaa/Data-Engineering-for-AI-System-DAICO/blob/main/notebooks/01_02_data_ingestion_delta_lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SDAIA** **Books** **Platform**

A data engineering platform for validating, streaming, and storing book registration data submitted by publishers across Saudi Arabia.

# Data Ingestion and Delta Lake

This notebook presents the implementation of the **Data Ingestion** and **Delta Lakehouse** components for the SDAIA Books Platform.

The implementation includes:

- Data validation using **Pydantic**.
- Real-time data streaming with **Apache Kafka** (Producer & Consumer).
- Delta Lake **Bronze**, **Silver**, and **Gold** layers.
- **MERGE (Upsert)** using `book_id` as the business key.
- **Schema Enforcement** demonstration to validate schema consistency.

This notebook corresponds to **Parts 1 & 2** of the project deliverables.

In [ ]:
!apt-get update -qq

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [ ]:
!apt-get install -y openjdk-17-jdk-headless

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openjdk-17-jdk-headless is already the newest version (17.0.19+10-1~22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 118 not upgraded.

In [ ]:
!pip install kafka-python pydantic faker

Requirement already satisfied: kafka-python in /usr/local/lib/python3.12/dist-packages (3.0.9)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.13.4)
Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.32.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.4.2)

In [ ]:
import pandas as pd
import random
from faker import Faker

fake = Faker()

# Make results reproducible
Faker.seed(42)
random.seed(42)

In [ ]:
publisher_names = [
    "Jarir Publishing",
    "Obeikan Publishing",
    "King Fahad National Library",
    "Dar Al-Minhaj",
    "Saudi Research Publishing"
]

publisher_cities = [
    "Riyadh",
    "Jeddah",
    "Dammam",
    "Madinah",
    "Abha"
]

categories = [
    "Artificial Intelligence",
    "Data Science",
    "Cybersecurity",
    "Education",
    "Government",
    "Culture",
    "History"
]

languages = ["Arabic", "English"]

records = []

for book_id in range(1, 101):

    isbn = f"978603{random.randint(1000000,9999999)}"

    records.append({
        "book_id": book_id,
        "isbn": isbn,
        "title": fake.sentence(nb_words=4).replace(".", ""),
        "author": fake.name(),
        "publisher_name": random.choice(publisher_names),
        "publisher_city": random.choice(publisher_cities),
        "category": random.choice(categories),
        "language": random.choice(languages),
        "publication_year": random.randint(2015, 2026),
        "submission_date": fake.date_this_year().strftime("%Y-%m-%d")
    })

df = pd.DataFrame(records)

df.head()

,book_id,isbn,title,author,publisher_name,publisher_city,category,language,publication_year,submission_date
0,1,9786032867825,Agent every,Noah Rhodes,Jarir Publishing,Dammam,Data Science,Arabic,2017,2026-06-30
1,2,9786032719583,Opportunity all,David Guzman,Saudi Research Publishing,Riyadh,Government,English,2015,2026-04-24
2,3,9786031499914,Information last everything thank serve,Jay Ramirez,Jarir Publishing,Jeddah,Data Science,Arabic,2023,2026-02-13
3,4,9786034335942,Bill here grow gas,Andrew Stevens,Saudi Research Publishing,Madinah,Data Science,English,2024,2026-01-26
4,5,9786035667265,Bad fall pick those,Corey Jones,Jarir Publishing,Jeddah,Culture,English,2020,2026-05-14

In [ ]:
# Missing ISBN
df.loc[0, "isbn"] = None

# Empty title
df.loc[1, "title"] = ""

# Unsupported language
df.loc[2, "language"] = "French"

# Future publication year
df.loc[3, "publication_year"] = 2050

# Invalid date format
df.loc[4, "submission_date"] = "2026/15/40"

df.head()

,book_id,isbn,title,author,publisher_name,publisher_city,category,language,publication_year,submission_date
0,1,None,Agent every,Noah Rhodes,Jarir Publishing,Dammam,Data Science,Arabic,2017,2026-06-30
1,2,9786032719583,,David Guzman,Saudi Research Publishing,Riyadh,Government,English,2015,2026-04-24
2,3,9786031499914,Information last everything thank serve,Jay Ramirez,Jarir Publishing,Jeddah,Data Science,French,2023,2026-02-13
3,4,9786034335942,Bill here grow gas,Andrew Stevens,Saudi Research Publishing,Madinah,Data Science,English,2050,2026-01-26
4,5,9786035667265,Bad fall pick those,Corey Jones,Jarir Publishing,Jeddah,Culture,English,2020,2026/15/40

In [ ]:
df.to_csv("books_data.csv", index=False)

print("Dataset created successfully!")
print(f"Total records: {len(df)}")

Dataset created successfully!
Total records: 100

In [ ]:
from pydantic import BaseModel, Field, ValidationError, field_validator
from datetime import datetime

In [ ]:
class BookRecord(BaseModel):
    book_id: int = Field(gt=0)
    isbn: str
    title: str
    author: str
    publisher_name: str
    publisher_city: str
    category: str
    language: str
    publication_year: int
    submission_date: str

    @field_validator("isbn")
    @classmethod
    def validate_isbn(cls, value):
        if not value:
            raise ValueError("ISBN cannot be empty.")
        return value

    @field_validator("title")
    @classmethod
    def validate_title(cls, value):
        if not value.strip():
            raise ValueError("Title cannot be empty.")
        return value

    @field_validator("language")
    @classmethod
    def validate_language(cls, value):
        if value not in ["Arabic", "English"]:
            raise ValueError("Language must be Arabic or English.")
        return value

    @field_validator("publication_year")
    @classmethod
    def validate_year(cls, value):
        current_year = datetime.now().year
        if value > current_year:
            raise ValueError("Publication year cannot be in the future.")
        return value

    @field_validator("submission_date")
    @classmethod
    def validate_date(cls, value):
        datetime.strptime(value, "%Y-%m-%d")
        return value

In [ ]:
valid_records = []
invalid_records = []

for _, row in df.iterrows():
    try:
        record = BookRecord(**row.to_dict())
        valid_records.append(record.model_dump())
    except ValidationError as e:
        invalid_records.append({
            **row.to_dict(),
            "error": str(e)
        })

valid_df = pd.DataFrame(valid_records)
invalid_df = pd.DataFrame(invalid_records)

print(f"✅ Valid Records: {len(valid_df)}")
print(f"❌ Invalid Records: {len(invalid_df)}")

✅ Valid Records: 95
❌ Invalid Records: 5

In [ ]:
valid_df.to_csv("valid_books.csv", index=False)
invalid_df.to_csv("rejected_books.csv", index=False)

print("Files saved successfully!")

print(f"Valid records: {len(valid_df)}")
print(f"Invalid records: {len(invalid_df)}")

Files saved successfully!
Valid records: 95
Invalid records: 5

In [ ]:
!wget -q https://archive.apache.org/dist/kafka/3.7.0/kafka_2.13-3.7.0.tgz
!tar -xzf kafka_2.13-3.7.0.tgz

^C

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

In [ ]:
%cd kafka_2.13-3.7.0

/content/kafka_2.13-3.7.0

In [ ]:
import os

cluster_id = os.popen("bin/kafka-storage.sh random-uuid").read().strip()

print(cluster_id)

In [ ]:
!bin/kafka-storage.sh format -t $cluster_id -c config/kraft/server.properties

Error: Could not find or load main class kafka.tools.StorageTool
Caused by: java.lang.ClassNotFoundException: kafka.tools.StorageTool

In [ ]:
!rm -rf kafka_2.13-3.7.0
!rm -f kafka_2.13-3.7.0.tgz

In [ ]:
!wget https://archive.apache.org/dist/kafka/3.7.0/kafka_2.13-3.7.0.tgz

--2026-07-22 15:40:35--  https://archive.apache.org/dist/kafka/3.7.0/kafka_2.13-3.7.0.tgz
Resolving archive.apache.org (archive.apache.org)... 65.108.204.189, 2a01:4f9:1a:a084::2
Connecting to archive.apache.org (archive.apache.org)|65.108.204.189|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 119028138 (114M) [application/x-gzip]
Saving to: ‘kafka_2.13-3.7.0.tgz’

kafka_2.13-3.7.0.tg 100%[===================>] 113.51M   123KB/s    in 14m 49s

2026-07-22 15:55:25 (131 KB/s) - ‘kafka_2.13-3.7.0.tgz’ saved [119028138/119028138]

In [ ]:
!tar -xzf kafka_2.13-3.7.0.tgz

In [ ]:
%cd kafka_2.13-3.7.0

/content/kafka_2.13-3.7.0/kafka_2.13-3.7.0

In [ ]:
import os

cluster_id = os.popen("bin/kafka-storage.sh random-uuid").read().strip()
print(cluster_id)

umQ5Ne1vQNqFsLcglYsEcA

In [ ]:
!bin/kafka-storage.sh format -t $cluster_id -c config/kraft/server.properties

metaPropertiesEnsemble=MetaPropertiesEnsemble(metadataLogDir=Optional.empty, dirs={/tmp/kraft-combined-logs: EMPTY})
Formatting /tmp/kraft-combined-logs with metadata.version 3.7-IV4.

In [ ]:
import subprocess
import time

broker = subprocess.Popen(
    ["bin/kafka-server-start.sh", "config/kraft/server.properties"]
)

time.sleep(10)

print("Kafka Broker started!")

In [ ]:
import subprocess
import time

broker = subprocess.Popen(
    ["bin/kafka-server-start.sh", "config/kraft/server.properties"]
)

time.sleep(10)

print("Kafka Broker started!")

Kafka Broker started!

In [ ]:
!bin/kafka-topics.sh \
  --create \
  --topic books \
  --bootstrap-server localhost:9092

Created topic books.

In [ ]:
from kafka import KafkaProducer
import pandas as pd
import json


# Step 1: Create a Kafka Producer
producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda x: json.dumps(x).encode("utf-8")
)

# Step 2: Load the validated dataset
valid_books = pd.read_csv("/content/valid_books.csv")


# Step 3: Send each record to the Kafka topic
for _, record in valid_books.iterrows():
    producer.send("books", value=record.to_dict())


# Step 4: Ensure all messages are delivered
producer.flush()

print(f"Successfully sent {len(valid_books)} records to the 'books' topic.")

Successfully sent 95 records to the 'books' topic.

In [ ]:
from kafka import KafkaConsumer
import json


# Step 1: Create a Kafka Consumer
consumer = KafkaConsumer(
    "books",
    bootstrap_servers="localhost:9092",
    auto_offset_reset="earliest",
    enable_auto_commit=True,
    value_deserializer=lambda x: json.loads(x.decode("utf-8"))
)

print("Reading records from Kafka...\n")

# Step 2: Read records from Kafka
count = 0

for message in consumer:
    print(message.value)
    count += 1

    # Stop after reading 95 records
    if count == 95:
        break

consumer.close()

print(f"\nSuccessfully consumed {count} records.")

/tmp/ipykernel_2932/2806510815.py:6: DeprecationWarning: value_deserializer does not implement kafka.serializer.Deserializer
  consumer = KafkaConsumer(
WARNING:kafka.coordinator.consumer:group_id is None: disabling auto-commit.

Reading records from Kafka...

{'book_id': 6, 'isbn': 9786035661907, 'title': 'World talk term', 'author': 'Jesse Flowers', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Jeddah', 'category': 'History', 'language': 'English', 'publication_year': 2016, 'submission_date': '2026-02-02'}
{'book_id': 7, 'isbn': 9786032556017, 'title': 'Decide environment view possible', 'author': 'Carolyn Daniel', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Riyadh', 'category': 'Cybersecurity', 'language': 'English', 'publication_year': 2024, 'submission_date': '2026-02-03'}
{'book_id': 8, 'isbn': 9786035437923, 'title': 'Establish understand read detail', 'author': 'Randy Brown', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Madinah', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2021, 'submission_date': '2026-06-16'}
{'book_id': 9, 'isbn': 9786032322047, 'title': 'Husband at tree note', 'author': 'Christy Porter', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Dammam', 'category': 'History', 'language': 'English', 'publication_year': 2024, 'submission_date': '2026-06-28'}
{'book_id': 10, 'isbn': 9786034226067, 'title': 'Central cause seat much', 'author': 'Jessica Silva', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Riyadh', 'category': 'Culture', 'language': 'Arabic', 'publication_year': 2019, 'submission_date': '2026-03-15'}
{'book_id': 11, 'isbn': 9786032338687, 'title': 'Meeting before another', 'author': 'Mark Conner', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Riyadh', 'category': 'Education', 'language': 'English', 'publication_year': 2022, 'submission_date': '2026-03-27'}
{'book_id': 12, 'isbn': 9786037120868, 'title': 'His other', 'author': 'David Tran', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Dammam', 'category': 'Cybersecurity', 'language': 'Arabic', 'publication_year': 2025, 'submission_date': '2026-07-10'}
{'book_id': 13, 'isbn': 9786035479144, 'title': 'Race Mr', 'author': 'Martin Rodriguez', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Abha', 'category': 'Culture', 'language': 'Arabic', 'publication_year': 2023, 'submission_date': '2026-03-29'}
{'book_id': 14, 'isbn': 9786035107245, 'title': 'About reveal rest will', 'author': 'Katie Rodriguez', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Madinah', 'category': 'Education', 'language': 'English', 'publication_year': 2025, 'submission_date': '2026-05-07'}
{'book_id': 15, 'isbn': 9786034684531, 'title': 'Participant check several much', 'author': 'Kerry Smith', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Riyadh', 'category': 'Data Science', 'language': 'Arabic', 'publication_year': 2020, 'submission_date': '2026-03-07'}
{'book_id': 16, 'isbn': 9786037730428, 'title': 'Born guy', 'author': 'Dr. Cynthia Allen', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Riyadh', 'category': 'Data Science', 'language': 'English', 'publication_year': 2018, 'submission_date': '2026-04-25'}
{'book_id': 17, 'isbn': 9786039375710, 'title': 'Beat magazine', 'author': 'Philip Cannon', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Madinah', 'category': 'Data Science', 'language': 'English', 'publication_year': 2017, 'submission_date': '2026-01-26'}
{'book_id': 18, 'isbn': 9786035137722, 'title': 'Water close month parent', 'author': 'Tanya Campos', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Abha', 'category': 'Cybersecurity', 'language': 'English', 'publication_year': 2024, 'submission_date': '2026-05-20'}
{'book_id': 19, 'isbn': 9786037700828, 'title': 'Human public health', 'author': 'Jocelyn Wright', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Jeddah', 'category': 'Data Science', 'language': 'English', 'publication_year': 2016, 'submission_date': '2026-01-13'}
{'book_id': 20, 'isbn': 9786031790481, 'title': 'Open discover', 'author': 'Benjamin Welch', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Jeddah', 'category': 'Culture', 'language': 'Arabic', 'publication_year': 2025, 'submission_date': '2026-02-16'}
{'book_id': 21, 'isbn': 9786038082668, 'title': 'Teacher audience', 'author': 'Michael Lewis', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Riyadh', 'category': 'Education', 'language': 'English', 'publication_year': 2024, 'submission_date': '2026-01-27'}
{'book_id': 22, 'isbn': 9786038852574, 'title': 'Office drug list imagine behind', 'author': 'Heather Jenkins', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Dammam', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2025, 'submission_date': '2026-06-24'}
{'book_id': 23, 'isbn': 9786032921859, 'title': 'Pull worker', 'author': 'James Morgan', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Dammam', 'category': 'History', 'language': 'English', 'publication_year': 2016, 'submission_date': '2026-06-24'}
{'book_id': 24, 'isbn': 9786035924115, 'title': 'Court movie cell', 'author': 'Joel Baxter', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Jeddah', 'category': 'Education', 'language': 'Arabic', 'publication_year': 2026, 'submission_date': '2026-01-16'}
{'book_id': 25, 'isbn': 9786035418934, 'title': 'Better present music address behavior', 'author': 'Cynthia Russell', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Jeddah', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2025, 'submission_date': '2026-04-08'}
{'book_id': 26, 'isbn': 9786036007072, 'title': 'Total clearly able hospital', 'author': 'Rachel Mitchell', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Abha', 'category': 'Data Science', 'language': 'Arabic', 'publication_year': 2020, 'submission_date': '2026-05-21'}
{'book_id': 27, 'isbn': 9786033710343, 'title': 'Product main couple design around', 'author': 'Amy Edwards', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Abha', 'category': 'Artificial Intelligence', 'language': 'English', 'publication_year': 2022, 'submission_date': '2026-01-11'}
{'book_id': 28, 'isbn': 9786031326765, 'title': 'Me system church whether', 'author': 'Cody Larson', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Dammam', 'category': 'History', 'language': 'English', 'publication_year': 2018, 'submission_date': '2026-05-17'}
{'book_id': 29, 'isbn': 9786031971823, 'title': 'Identify walk now', 'author': 'Amanda Miller', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Abha', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2026, 'submission_date': '2026-05-13'}
{'book_id': 30, 'isbn': 9786039153566, 'title': 'Mission various daughter respond draw', 'author': 'Michael Evans', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Abha', 'category': 'History', 'language': 'Arabic', 'publication_year': 2017, 'submission_date': '2026-03-05'}
{'book_id': 31, 'isbn': 9786038973915, 'title': 'Act perform', 'author': 'Ariel Medina', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Jeddah', 'category': 'Cybersecurity', 'language': 'English', 'publication_year': 2018, 'submission_date': '2026-04-13'}
{'book_id': 32, 'isbn': 9786034374754, 'title': 'Value thing these', 'author': 'Christopher Bass', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Madinah', 'category': 'Culture', 'language': 'English', 'publication_year': 2022, 'submission_date': '2026-05-23'}
{'book_id': 33, 'isbn': 9786039683481, 'title': 'Worker southern more property never', 'author': 'Ashley Humphrey', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Riyadh', 'category': 'Data Science', 'language': 'Arabic', 'publication_year': 2016, 'submission_date': '2026-02-23'}
{'book_id': 34, 'isbn': 9786036672134, 'title': 'Score choice', 'author': 'Daniel Cooper', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Abha', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2024, 'submission_date': '2026-05-19'}
{'book_id': 35, 'isbn': 9786034694634, 'title': 'Measure economy traditional', 'author': 'Mark Calderon', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Riyadh', 'category': 'Culture', 'language': 'Arabic', 'publication_year': 2018, 'submission_date': '2026-01-09'}
{'book_id': 36, 'isbn': 9786032130789, 'title': 'Side PM energy scientist', 'author': 'Jessica Smith', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Dammam', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2019, 'submission_date': '2026-01-16'}
{'book_id': 37, 'isbn': 9786039143903, 'title': 'Nation strong old', 'author': 'Cameron Parker', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Abha', 'category': 'Data Science', 'language': 'English', 'publication_year': 2018, 'submission_date': '2026-07-01'}
{'book_id': 38, 'isbn': 9786038935169, 'title': 'Together decide', 'author': 'Brian Deleon', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Jeddah', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2025, 'submission_date': '2026-06-28'}
{'book_id': 39, 'isbn': 9786038231838, 'title': 'Wind see understand door', 'author': 'Robert Thompson', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Madinah', 'category': 'Education', 'language': 'English', 'publication_year': 2026, 'submission_date': '2026-03-25'}
{'book_id': 40, 'isbn': 9786031908841, 'title': 'Say forward us', 'author': 'Sharon Cochran', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Riyadh', 'category': 'Education', 'language': 'English', 'publication_year': 2016, 'submission_date': '2026-02-23'}
{'book_id': 41, 'isbn': 9786035171761, 'title': 'Him although', 'author': 'Curtis Sellers', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Jeddah', 'category': 'Government', 'language': 'English', 'publication_year': 2017, 'submission_date': '2026-03-12'}
{'book_id': 42, 'isbn': 9786038077999, 'title': 'Development process huge', 'author': 'Benjamin Ayala', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Dammam', 'category': 'Education', 'language': 'Arabic', 'publication_year': 2016, 'submission_date': '2026-03-12'}
{'book_id': 43, 'isbn': 9786038434500, 'title': 'Hundred wonder movie voice boy', 'author': 'Cassandra Estes', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Riyadh', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2016, 'submission_date': '2026-02-23'}
{'book_id': 44, 'isbn': 9786034965789, 'title': 'Others generation', 'author': 'Jessica Joyce', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Madinah', 'category': 'Education', 'language': 'English', 'publication_year': 2018, 'submission_date': '2026-01-24'}
{'book_id': 45, 'isbn': 9786037728339, 'title': 'Couple and job mind southern', 'author': 'Teresa Mclaughlin', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Jeddah', 'category': 'Education', 'language': 'Arabic', 'publication_year': 2021, 'submission_date': '2026-02-09'}
{'book_id': 46, 'isbn': 9786035449368, 'title': 'Attorney professional form finish', 'author': 'Michelle Evans', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Dammam', 'category': 'Education', 'language': 'English', 'publication_year': 2017, 'submission_date': '2026-03-04'}
{'book_id': 47, 'isbn': 9786034185957, 'title': 'For recent never court', 'author': 'Jamie Adkins', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Jeddah', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2026, 'submission_date': '2026-02-05'}
{'book_id': 48, 'isbn': 9786036261415, 'title': 'Feeling nature a expert involve', 'author': 'Mary Marshall', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Riyadh', 'category': 'Government', 'language': 'English', 'publication_year': 2023, 'submission_date': '2026-03-31'}
{'book_id': 49, 'isbn': 9786039910817, 'title': 'Memory soldier where', 'author': 'Mary Campbell', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Riyadh', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2017, 'submission_date': '2026-05-15'}
{'book_id': 50, 'isbn': 9786032149597, 'title': 'Friend stand seem pull different', 'author': 'Alexander Sanchez', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Riyadh', 'category': 'Culture', 'language': 'Arabic', 'publication_year': 2021, 'submission_date': '2026-04-06'}
{'book_id': 51, 'isbn': 9786033011363, 'title': 'Lay though', 'author': 'Michelle Cruz', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Jeddah', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2024, 'submission_date': '2026-03-22'}
{'book_id': 52, 'isbn': 9786032375453, 'title': 'Prevent accept seem', 'author': 'Ashley Coleman', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Abha', 'category': 'Government', 'language': 'English', 'publication_year': 2019, 'submission_date': '2026-02-05'}
{'book_id': 53, 'isbn': 9786034426900, 'title': 'Let newspaper true building card', 'author': 'Joseph Hansen', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Jeddah', 'category': 'Cybersecurity', 'language': 'English', 'publication_year': 2017, 'submission_date': '2026-03-06'}
{'book_id': 54, 'isbn': 9786036033115, 'title': 'Partner rest measure store', 'author': 'Stephanie Manning', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Dammam', 'category': 'History', 'language': 'Arabic', 'publication_year': 2015, 'submission_date': '2026-04-06'}
{'book_id': 55, 'isbn': 9786038688755, 'title': 'Seem style everyone', 'author': 'Kari Allen', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Abha', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2023, 'submission_date': '2026-03-30'}
{'book_id': 56, 'isbn': 9786034576135, 'title': 'Doctor from throw', 'author': 'Chris Reyes', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Dammam', 'category': 'Data Science', 'language': 'English', 'publication_year': 2016, 'submission_date': '2026-01-31'}
{'book_id': 57, 'isbn': 9786035098412, 'title': 'Ask imagine my', 'author': 'Daniel Fisher', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Dammam', 'category': 'Data Science', 'language': 'English', 'publication_year': 2023, 'submission_date': '2026-07-02'}
{'book_id': 58, 'isbn': 9786036075395, 'title': 'Watch affect thing offer local', 'author': 'Elizabeth Price', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Abha', 'category': 'Artificial Intelligence', 'language': 'English', 'publication_year': 2025, 'submission_date': '2026-06-30'}
{'book_id': 59, 'isbn': 9786032737893, 'title': 'Mrs same son today', 'author': 'Don Tucker MD', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Dammam', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2026, 'submission_date': '2026-05-16'}
{'book_id': 60, 'isbn': 9786033607983, 'title': 'Right subject try wonder', 'author': 'Susan Vargas', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Dammam', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2026, 'submission_date': '2026-05-14'}
{'book_id': 61, 'isbn': 9786036752576, 'title': 'Poor career', 'author': 'Anthony Gray', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Dammam', 'category': 'Government', 'language': 'English', 'publication_year': 2019, 'submission_date': '2026-02-12'}
{'book_id': 62, 'isbn': 9786031852264, 'title': 'Front they everything week', 'author': 'Ruben Ruiz', 'publisher_name': 'Jarir Publishing', 'publisher_city': 'Madinah', 'category': 'History', 'language': 'English', 'publication_year': 2015, 'submission_date': '2026-06-01'}
{'book_id': 63, 'isbn': 9786031059486, 'title': 'Yourself glass', 'author': 'Rachael Pearson', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Jeddah', 'category': 'Culture', 'language': 'English', 'publication_year': 2017, 'submission_date': '2026-06-02'}
{'book_id': 64, 'isbn': 9786038412769, 'title': 'Current after charge', 'author': 'Michael Elliott', 'publisher_name': 'Saudi Research Publishing', 'publisher_city': 'Madinah', 'category': 'Government', 'language': 'Arabic', 'publication_year': 2016, 'submission_date': '2026-02-14'}
{'book_id': 65, 'isbn': 9786032262382, 'title': 'Short cold parent', 'author': 'Ashley Weiss', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Abha', 'category': 'Artificial Intelligence', 'language': 'English', 'publication_year': 2024, 'submission_date': '2026-07-14'}
{'book_id': 66, 'isbn': 9786033484601, 'title': 'Official up', 'author': 'Susan Brooks', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Jeddah', 'category': 'Artificial Intelligence', 'language': 'English', 'publication_year': 2020, 'submission_date': '2026-07-10'}
{'book_id': 67, 'isbn': 9786031669324, 'title': 'Away real physical', 'author': 'Raymond Jefferson', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Jeddah', 'category': 'Culture', 'language': 'Arabic', 'publication_year': 2025, 'submission_date': '2026-05-02'}
{'book_id': 68, 'isbn': 9786032724590, 'title': 'Someone not American', 'author': 'Mary Jones', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Abha', 'category': 'History', 'language': 'English', 'publication_year': 2024, 'submission_date': '2026-05-11'}
{'book_id': 69, 'isbn': 9786033592974, 'title': 'Support state', 'author': 'Tyler Reid', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Jeddah', 'category': 'History', 'language': 'Arabic', 'publication_year': 2021, 'submission_date': '2026-06-17'}
{'book_id': 70, 'isbn': 9786031415846, 'title': 'Itself safe whole', 'author': 'Robert Medina', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Dammam', 'category': 'History', 'language': 'English', 'publication_year': 2025, 'submission_date': '2026-04-08'}
{'book_id': 71, 'isbn': 9786035163555, 'title': 'Stay or focus early', 'author': 'Diana Hayes', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Jeddah', 'category': 'History', 'language': 'Arabic', 'publication_year': 2021, 'submission_date': '2026-06-01'}
{'book_id': 72, 'isbn': 9786031649691, 'title': 'Particular her agreement surface consider', 'author': 'Robert Peterson', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Jeddah', 'category': 'Data Science', 'language': 'English', 'publication_year': 2020, 'submission_date': '2026-06-27'}
{'book_id': 73, 'isbn': 9786036120253, 'title': 'New might course', 'author': 'Jason Peters', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Jeddah', 'category': 'Artificial Intelligence', 'language': 'Arabic', 'publication_year': 2021, 'submission_date': '2026-02-18'}
{'book_id': 74, 'isbn': 9786036507321, 'title': 'Position make society behavior', 'author': 'Michael Torres', 'publisher_name': 'King Fahad National Library', 'publisher_city': 'Riyadh', 'category': 'History', 'language': 'English', 'publication_year': 2020, 'submission_date': '2026-04-28'}
{'book_id': 75, 'isbn': 9786039546409, 'title': 'Network gas you nearly', 'author': 'Jesse Parker', 'publisher_name': 'Dar Al-Minhaj', 'publisher_city': 'Abha', 'category': 'Cybersecurity', 'language': 'Arabic', 'publication_year': 2016, 'submission_date': '2026-02-16'}
{'book_id': 76, 'isbn': 9786035382463, 'title': 'Firm sea week', 'author': 'Cheryl Rodgers', 'publisher_name': 'Obeikan Publishing', 'publisher_city': 'Abha', 'category': 'Cybersecurity', 'language': 'Arabic', 'publication_year': 2016, 'submission_date': '2026-02-25'}

In [ ]:
!pip install -q pyspark==3.5.0 delta-spark==3.2.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.9/316.9 MB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.5/200.5 kB 15.6 MB/s eta 0:00:00
  Building wheel for pyspark (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dataproc-spark-connect 1.1.0 requires pyspark[connect]~=4.0.0, but you have pyspark 3.5.0 which is incompatible.

In [ ]:
from pyspark.sql import SparkSession
from delta import configure_spark_with_delta_pip

builder = (
    SparkSession.builder
    .appName("SDAIA Books Pipeline")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
)

spark = configure_spark_with_delta_pip(builder).getOrCreate()

print("Spark Session is ready!")

Spark Session is ready!

In [ ]:
from pyspark.sql.functions import current_timestamp


# Step 1: Load the validated dataset
bronze_df = spark.read.csv(
    "/content/valid_books.csv",
    header=True,
    inferSchema=True
)


# Step 2: Add ingestion timestamp
bronze_df = bronze_df.withColumn(
    "ingestion_time",
    current_timestamp()
)


# Step 3: Save as Delta Bronze table
bronze_df.write \
    .format("delta") \
    .mode("overwrite") \
    .save("/content/delta/bronze")

print("Bronze layer created successfully!")

Bronze layer created successfully!

In [ ]:
bronze = spark.read.format("delta").load("/content/delta/bronze")

print(f"Number of records: {bronze.count()}")

bronze.show(5, truncate=False)

Number of records: 95
+-------+-------------+--------------------------------+--------------+-------------------------+--------------+-------------+--------+----------------+---------------+--------------------------+
|book_id|isbn         |title                           |author        |publisher_name           |publisher_city|category     |language|publication_year|submission_date|ingestion_time            |
+-------+-------------+--------------------------------+--------------+-------------------------+--------------+-------------+--------+----------------+---------------+--------------------------+
|6      |9786035661907|World talk term                 |Jesse Flowers |Obeikan Publishing       |Jeddah        |History      |English |2016            |2026-02-02     |2026-07-22 16:13:55.682499|
|7      |9786032556017|Decide environment view possible|Carolyn Daniel|Dar Al-Minhaj            |Riyadh        |Cybersecurity|English |2024            |2026-02-03     |2026-07-22 16:13:55.682499|
|8      |9786035437923|Establish understand read detail|Randy Brown   |Jarir Publishing         |Madinah       |Government   |Arabic  |2021            |2026-06-16     |2026-07-22 16:13:55.682499|
|9      |9786032322047|Husband at tree note            |Christy Porter|Saudi Research Publishing|Dammam        |History      |English |2024            |2026-06-28     |2026-07-22 16:13:55.682499|
|10     |9786034226067|Central cause seat much         |Jessica Silva |Jarir Publishing         |Riyadh        |Culture      |Arabic  |2019            |2026-03-15     |2026-07-22 16:13:55.682499|
+-------+-------------+--------------------------------+--------------+-------------------------+--------------+-------------+--------+----------------+---------------+--------------------------+
only showing top 5 rows

In [ ]:
from pyspark.sql.functions import col


# Step 1: Read Bronze layer
silver_df = spark.read.format("delta").load("/content/delta/bronze")


# Step 2: Clean the data
silver_df = (
    silver_df
    .dropDuplicates()
    .withColumn("publication_year", col("publication_year").cast("int"))
    .withColumn("submission_date", col("submission_date").cast("date"))
)


# Step 3: Save as Delta Silver table
silver_df.write \
    .format("delta") \
    .mode("overwrite") \
    .save("/content/delta/silver")

print("Silver layer created successfully!")

Silver layer created successfully!

In [ ]:
silver = spark.read.format("delta").load("/content/delta/silver")

print(f"Number of records: {silver.count()}")

silver.show(5, truncate=False)

Number of records: 95
+-------+-------------+---------------------------------+---------------+---------------------------+--------------+-----------------------+--------+----------------+---------------+--------------------------+
|book_id|isbn         |title                            |author         |publisher_name             |publisher_city|category               |language|publication_year|submission_date|ingestion_time            |
+-------+-------------+---------------------------------+---------------+---------------------------+--------------+-----------------------+--------+----------------+---------------+--------------------------+
|46     |9786035449368|Attorney professional form finish|Michelle Evans |Dar Al-Minhaj              |Dammam        |Education              |English |2017            |2026-03-04     |2026-07-22 16:13:55.682499|
|90     |9786037705062|Play man before girl             |Michael Hodge  |Obeikan Publishing         |Jeddah        |Culture                |Arabic  |2016            |2026-03-08     |2026-07-22 16:13:55.682499|
|55     |9786038688755|Seem style everyone              |Kari Allen     |Saudi Research Publishing  |Abha          |Artificial Intelligence|Arabic  |2023            |2026-03-30     |2026-07-22 16:13:55.682499|
|63     |9786031059486|Yourself glass                   |Rachael Pearson|King Fahad National Library|Jeddah        |Culture                |English |2017            |2026-06-02     |2026-07-22 16:13:55.682499|
|96     |9786035652512|During necessary himself two     |Sherry Shields |Saudi Research Publishing  |Madinah       |Culture                |Arabic  |2019            |2026-02-25     |2026-07-22 16:13:55.682499|
+-------+-------------+---------------------------------+---------------+---------------------------+--------------+-----------------------+--------+----------------+---------------+--------------------------+
only showing top 5 rows

In [ ]:
from pyspark.sql.functions import count


# Step 1: Read Silver layer
silver = spark.read.format("delta").load("/content/delta/silver")


# Step 2: Create Gold layer
# Count books by category and language
gold_df = (
    silver
    .groupBy("category", "language")
    .agg(count("*").alias("number_of_books"))
)


# Step 3: Save as Delta Gold table
gold_df.write \
    .format("delta") \
    .mode("overwrite") \
    .save("/content/delta/gold")

print("Gold layer created successfully!")

Gold layer created successfully!

In [ ]:
gold = spark.read.format("delta").load("/content/delta/gold")

gold.orderBy("category", "language").show(truncate=False)

+-----------------------+--------+---------------+
|category               |language|number_of_books|
+-----------------------+--------+---------------+
|Artificial Intelligence|Arabic  |8              |
|Artificial Intelligence|English |5              |
|Culture                |Arabic  |9              |
|Culture                |English |5              |
|Cybersecurity          |Arabic  |3              |
|Cybersecurity          |English |7              |
|Data Science           |Arabic  |5              |
|Data Science           |English |10             |
|Education              |Arabic  |8              |
|Education              |English |7              |
|Government             |Arabic  |8              |
|Government             |English |5              |
|History                |Arabic  |6              |
|History                |English |9              |
+-----------------------+--------+---------------+

In [42]:
from pyspark.sql import Row
from pyspark.sql.functions import current_timestamp, to_date

# Read the schema from Silver
silver = spark.read.format("delta").load("/content/delta/silver")

updates = [
    (
        46,
        "9786035449368",
        "Updated Book Title",
        "Michelle Evans",
        "Dar Al-Minhaj",
        "Dammam",
        "Education",
        "English",
        2025,
        "2026-07-22"
    )
]

updates_df = spark.createDataFrame(
    updates,
    schema="""
    book_id INT,
    isbn STRING,
    title STRING,
    author STRING,
    publisher_name STRING,
    publisher_city STRING,
    category STRING,
    language STRING,
    publication_year INT,
    submission_date STRING
    """
)

updates_df = (
    updates_df
    .withColumn("submission_date", to_date("submission_date"))
    .withColumn("ingestion_time", current_timestamp())
)

updates_df.show()

+-------+-------------+------------------+--------------+--------------+--------------+---------+--------+----------------+---------------+--------------------+
|book_id|         isbn|             title|        author|publisher_name|publisher_city| category|language|publication_year|submission_date|      ingestion_time|
+-------+-------------+------------------+--------------+--------------+--------------+---------+--------+----------------+---------------+--------------------+
|     46|9786035449368|Updated Book Title|Michelle Evans| Dar Al-Minhaj|        Dammam|Education| English|            2025|     2026-07-22|2026-07-22 17:16:...|
+-------+-------------+------------------+--------------+--------------+--------------+---------+--------+----------------+---------------+--------------------+

MERGE

The following example demonstrates a Delta Lake MERGE (Upsert) operation using `book_id` as the business key.

In [43]:
from delta.tables import DeltaTable

silver_table = DeltaTable.forPath(spark, "/content/delta/silver")

(
    silver_table.alias("target")
    .merge(
        updates_df.alias("source"),
        "target.book_id = source.book_id"
    )
    .whenMatchedUpdateAll()
    .whenNotMatchedInsertAll()
    .execute()
)

print("Merge completed successfully!")

Merge completed successfully!

In [44]:
silver = spark.read.format("delta").load("/content/delta/silver")

silver.filter("book_id = 46").show(truncate=False)

+-------+-------------+------------------+--------------+--------------+--------------+---------+--------+----------------+---------------+--------------------------+
|book_id|isbn         |title             |author        |publisher_name|publisher_city|category |language|publication_year|submission_date|ingestion_time            |
+-------+-------------+------------------+--------------+--------------+--------------+---------+--------+----------------+---------------+--------------------------+
|46     |9786035449368|Updated Book Title|Michelle Evans|Dar Al-Minhaj |Dammam        |Education|English |2025            |2026-07-22     |2026-07-22 17:18:04.802447|
+-------+-------------+------------------+--------------+--------------+--------------+---------+--------+----------------+---------------+--------------------------+

## Schema Enforcement
The following example demonstrates Delta Lake schema enforcement by attempting to write data that does not match the existing table schema.

In [45]:
from pyspark.sql import Row

# Create invalid data with an extra column
invalid_data = [
    Row(
        book_id=999,
        isbn="9786030000000",
        title="Invalid Book",
        author="Test Author",
        publisher_name="Test Publisher",
        publisher_city="Riyadh",
        category="Education",
        language="English",
        publication_year=2025,
        submission_date="2026-07-22",
        extra_column="This column should not exist"
    )
]

invalid_df = spark.createDataFrame(invalid_data)

try:
    invalid_df.write \
        .format("delta") \
        .mode("append") \
        .save("/content/delta/silver")

    print("Schema accepted.")

except Exception as e:
    print("Schema Enforcement is working!")
    print(e)

Schema Enforcement is working!
[DELTA_FAILED_TO_MERGE_FIELDS] Failed to merge fields 'book_id' and 'book_id'